version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./frontend/tvs_frontend:/frontend/tvs_frontend
    ports:
      - 2222:2222
    env_file:
      - ./.env.dev
    environment:
      - WATCHPACK_POLLING=true
    working_dir: /frontend/tvs_frontend
    command: npm run dev

  backend:
    build:
      context: ./backend
    command: uvicorn main:app --host 0.0.0.0 --port 8000  --reload
    tty: true
    volumes:
      - ./backend:/backend
    expose:
      - 8000
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:POSTGRES_DB@db:5432/tvs

  db:
    image: postgres
    env_file:
      - ./.env.dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tvs
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

  pgadmin:
    image: dpage/pgadmin4
    expose:
      - 6060
    ports:
      - 6060:80
    environment:
      PGADMIN_DEFAULT_EMAIL: yumu31pj@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 5kvus2zz6avg
    depends_on:
      - db

volumes:
  postgres_data: